[package]
name = "git_lfs_wrangler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
eframe = "0.28.1"
egui = "0.28.1"
regex = "1.10.6"
serde_json = "1.0.128"
